### ISSUE TITLE
cant use su command

### ISSUE THREAD

**Issue by pryan1check** [Swind/pure-python-adb#26]
device.shell('su cd /data/data/<app_pkg>/databases/')
blocking code. How to make request with su??

**Comment by Swind** [comment]
Hi pryan1check:
In order to use `su` command, you need to root your device.
You can try to use [Magisk](https://github.com/topjohnwu/Magisk) .

**Comment by pryan1check** [comment]
@Swind i alredy have root, but when i call commands with "su", my code stuck

**Comment by Swind** [comment]
Hi @pryan1check 

The root cause is that when you use 'su' command, 
the return value doesn't contain EOF and the shell will enter `interactive mode`.
(The return value is similar to this `ASUS_X00R_3:/ `) .

If you want to execute command as root,
you can try this command

`print(device.shell("su -c 'cat /system/build.prop | grep product'"))`

Thanks
